### PR TITLE
Budget

### PR DESCRIPTION
**Pull request by giarcieri**

### CODE REVIEW

**Review by DanielHettegger — COMMENTED** [review]
It looks good, and the tests are all passing. 

Before we add this I think we should add an observation to the environment showing the remaining budget and time left until the budget is refreshed. Otherwise, the remaining budget is unknown to the agent if it does not keep track of the last 5 timestep's spending.

**Comment by giarcieri** [comment]
Good point, I will add this

**Comment by giarcieri** [comment]
Added

**Comment by giarcieri** [comment]
Thanks Daniel!

**Pull request merged**
